### ISSUE TITLE
NPM start creates a wrong dependency inside boot.js

### ISSUE THREAD

**Issue by FrancescoFontana** [mschwarzmueller/angular-2-beta-boilerplate#20]
Hi,
I was trying to install the boilerplate, but when I launch npm start, the compiled boot.js file contains 
`System.register(['angular2/platform/browser', "./app.component.ts"]`

Of course `app.component.ts.js` doesn't exists, so I get a 404. If I change it to 
`System.register(['angular2/platform/browser', "./app.component"]`
then everything works fine, unless I compile it again, of course.

Am I doing something wrong?

Thanks
Francesco

**Comment by mschwarzmueller** [comment]
Hi Francesco,
that's really a strange thing, because as you can see in the code, there is no '.ts' at the end: https://github.com/mschwarzmueller/angular-2-beta-boilerplate/blob/master/dev/boot.ts
I'd assume it might have something to do with your development environment or editor. Maybe it automatically adds this extension?

**Comment by FrancescoFontana** [comment]
I'm using IntellijIdea 15 on windows. 
You are right, the file name get replaced by the editor when I copy the files outside the folder. Seems that Intellij checks for file references and "fix it". That caused the issue.

Thanks for your really quick reply

Francesco
